# Generated by Django 4.1.1 on 2022-09-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_word", models.CharField(max_length=4, verbose_name="слово")),
            ],
            options={
                "verbose_name": "Cлово из базы",
                "verbose_name_plural": "Слова из базы",
                "ordering": ["base_word"],
            },
        ),
        migrations.CreateModel(
            name="InputWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=4, verbose_name="слово")),
            ],
            options={
                "verbose_name": "Введенное cлово",
                "verbose_name_plural": "Введеные слова",
                "ordering": ["word"],
            },
        ),
    ]
