# Generated by Django 4.1.1 on 2022-09-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputword",
            name="buls",
            field=models.IntegerField(default=0, verbose_name="быки"),
        ),
        migrations.AddField(
            model_name="inputword",
            name="cows",
            field=models.IntegerField(default=0, verbose_name="коровы"),
        ),
    ]
