# Generated by Django 4.1.1 on 2022-09-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_app", "0002_inputword_buls_inputword_cows"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inputword",
            options={
                "ordering": ["pk"],
                "verbose_name": "Введенное cлово",
                "verbose_name_plural": "Введеные слова",
            },
        ),
    ]
