# Generated by Django 4.1.1 on 2022-09-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_app", "0003_alter_inputword_options"),
    ]

    operations = [
        migrations.DeleteModel(name="InputWord",),
        migrations.AlterModelOptions(
            name="basewords",
            options={
                "ordering": ["base_word"],
                "verbose_name": "Cлово из базы данных",
                "verbose_name_plural": "Слова из базы данных",
            },
        ),
    ]
